In [4]:
## NUmpy Library:
##--->used to process N-Dimensional data
import numpy as np
li=[1,2,3,4]
a=np.array(li)
b=np.arange(15)
print

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
rn=np.random.randint(0,100,size=10)
rn

array([38, 34, 22, 43, 88, 27, 97, 78, 72,  8])

In [8]:
rn3=np.random.randint(0,100,size=(2,4,4))
rn3

array([[[19, 26, 79, 91],
        [71, 23, 55, 34],
        [61, 91, 36, 94],
        [45, 85, 18, 75]],

       [[23, 12, 31, 44],
        [46, 39, 95, 60],
        [70, 95, 17,  9],
        [75, 84, 33, 27]]])

In [9]:
rn2=np.random.randint(0,100,size=(2,4))
rn2

array([[26, 37,  1, 78],
       [98, 58, 24, 75]])

In [13]:
rn3.ndim
rn3.size
rn3.shape
rn3.dtype

dtype('int32')

In [3]:
import pandas as pd
internal={'s1':25,'s2':21,'s3':15}
internal=pd.Series(internal)
internal1={'s1':15,'s2':22,'s3':25}
internal1=pd.Series(internal1)
internal

s1    25
s2    21
s3    15
dtype: int64

In [4]:
internal1

s1    15
s2    22
s3    25
dtype: int64

In [5]:
final={'internal1':internal,'internal2':internal1}
final=pd.DataFrame(final)
final

internal1  internal2
s1         25         15
s2         21         22
s3         15         25

In [ ]:
import pandas as pd 
# reading csv file data
income=pd.read_csv()